spring:
  application:
    name: rating
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/rating
    username: rating
    password: rating
  grpc:
    server:
      port: 9082
  cache:
    cache-names: rating-factors
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=10m

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
