spring:
  application:
    name: policy
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/policy
    username: policy
    password: policy
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379
  grpc:
    client:
      channels:
        rating:
          address: static://localhost:9082
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8180/realms/ubi

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
